# Generated by Django 6.0.4 on 2026-05-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomreport',
            name='symptom_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
