# Generated by Django 6.0.4 on 2026-04-27 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('workflows', '0002_alter_escalationrule_target_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_rules', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('WARNING', 'Warning'), ('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=20)),
                ('recommended_action', models.CharField(choices=[('SHOW_ADVICE', 'Show Advice'), ('CONTINUE_MONITORING', 'Continue Monitoring'), ('RECOMMEND_CONTACT', 'Recommend Contact'), ('ESCALATE_TO_DENTIST', 'Escalate To Dentist'), ('PRIORITIZE_APPOINTMENT', 'Prioritize Appointment')], max_length=40)),
                ('appointment_priority', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NONE', max_length=20)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='workflows.carestage')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='reports.symptomreport')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
