WORKFLOW_VALIDATED = "WORKFLOW_VALIDATED"
WORKFLOW_ACTIVATED = "WORKFLOW_ACTIVATED"
WORKFLOW_ARCHIVED = "WORKFLOW_ARCHIVED"
FOLLOW_UP_CASE_CREATED = "FOLLOW_UP_CASE_CREATED"
FOLLOW_UP_CASE_STATUS_CHANGED = "FOLLOW_UP_CASE_STATUS_CHANGED"
SYMPTOM_REPORT_SUBMITTED = "SYMPTOM_REPORT_SUBMITTED"
RISK_ASSESSMENT_CREATED = "RISK_ASSESSMENT_CREATED"
ADVICE_CREATED = "ADVICE_CREATED"
ESCALATION_CREATED = "ESCALATION_CREATED"
ESCALATION_UPDATED = "ESCALATION_UPDATED"
APPOINTMENT_CREATED = "APPOINTMENT_CREATED"
APPOINTMENT_UPDATED = "APPOINTMENT_UPDATED"

ACTION_CHOICES = (
    (WORKFLOW_VALIDATED, "Workflow validated"),
    (WORKFLOW_ACTIVATED, "Workflow activated"),
    (WORKFLOW_ARCHIVED, "Workflow archived"),
    (FOLLOW_UP_CASE_CREATED, "Follow-up case created"),
    (FOLLOW_UP_CASE_STATUS_CHANGED, "Follow-up case status changed"),
    (SYMPTOM_REPORT_SUBMITTED, "Symptom report submitted"),
    (RISK_ASSESSMENT_CREATED, "Risk assessment created"),
    (ADVICE_CREATED, "Advice created"),
    (ESCALATION_CREATED, "Escalation created"),
    (ESCALATION_UPDATED, "Escalation updated"),
    (APPOINTMENT_CREATED, "Appointment created"),
    (APPOINTMENT_UPDATED, "Appointment updated"),
)
