# Generated by Django 6.0.4 on 2026-04-26 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_day', models.PositiveIntegerField()),
                ('end_day', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['workflow', 'sort_order', 'start_day', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SymptomRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('condition', models.JSONField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('WARNING', 'Warning'), ('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=20)),
                ('recommended_action', models.CharField(choices=[('SHOW_ADVICE', 'Show Advice'), ('CONTINUE_MONITORING', 'Continue Monitoring'), ('RECOMMEND_CONTACT', 'Recommend Contact'), ('ESCALATE_TO_DENTIST', 'Escalate To Dentist'), ('PRIORITIZE_APPOINTMENT', 'Prioritize Appointment')], max_length=40)),
                ('appointment_priority', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NONE', max_length=20)),
                ('explanation', models.TextField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_rules', to='workflows.carestage')),
            ],
            options={
                'ordering': ['stage', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('PATIENT', 'Patient'), ('DENTIST', 'Dentist'), ('ADMIN', 'Admin')], default='DENTIST', max_length=20)),
                ('urgency', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='HIGH', max_length=20)),
                ('appointment_priority', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='HIGH', max_length=20)),
                ('message', models.TextField()),
                ('symptom_rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rule', to='workflows.symptomrule')),
            ],
            options={
                'ordering': ['symptom_rule', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('treatment_type', models.CharField(choices=[('POST_EXTRACTION', 'Post-Extraction Follow-Up')], default='POST_EXTRACTION', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='carestage',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.treatmentworkflow'),
        ),
        migrations.CreateModel(
            name='AIAdviceBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_topics', models.JSONField(blank=True, default=list)),
                ('forbidden_topics', models.JSONField(blank=True, default=list)),
                ('required_disclaimer', models.TextField(blank=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advice_boundaries', to='workflows.carestage')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advice_boundaries', to='workflows.treatmentworkflow')),
            ],
            options={
                'ordering': ['workflow', 'stage_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SymptomDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('data_type', models.CharField(choices=[('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('CHOICE', 'Choice'), ('TEXT', 'Text')], max_length=20)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_definitions', to='workflows.treatmentworkflow')),
            ],
            options={
                'ordering': ['workflow', 'key'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'key'), name='unique_symptom_key_per_workflow')],
            },
        ),
    ]
