# Generated by Django 6.0.4 on 2026-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationrule',
            name='target_role',
            field=models.CharField(choices=[('DENTIST', 'Dentist'), ('ADMIN', 'Admin')], default='DENTIST', max_length=20),
        ),
    ]
