# Generated by Django 6.0.4 on 2026-04-27 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decision_engine', '0001_initial'),
        ('escalations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PRIORITY_SUGGESTED', 'Priority suggested'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PRIORITY_SUGGESTED', max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('escalation_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='escalations.escalationcase')),
                ('follow_up_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.followupcase')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientprofile')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='decision_engine.riskassessment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
