# Generated by Django 6.0.4 on 2026-04-26 20:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_after_treatment', models.PositiveIntegerField()),
                ('pain_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('swelling', models.CharField(choices=[('NONE', 'None'), ('MILD', 'Mild'), ('SEVERE', 'Severe')], max_length=16)),
                ('bleeding', models.CharField(choices=[('NONE', 'None'), ('MILD', 'Mild'), ('SEVERE', 'Severe')], max_length=16)),
                ('fever', models.BooleanField(default=False)),
                ('bad_smell', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='symptom_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_up_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to='patients.followupcase')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
