# Generated by Django 6.0.4 on 2026-04-27 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decision_engine', '0001_initial'),
        ('patients', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In review'), ('WAITING_FOR_PATIENT', 'Waiting for patient'), ('APPOINTMENT_REQUIRED', 'Appointment required'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=32)),
                ('urgency', models.CharField(choices=[('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=20)),
                ('staff_response', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_escalation_cases', to=settings.AUTH_USER_MODEL)),
                ('follow_up_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_cases', to='patients.followupcase')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_cases', to='patients.patientprofile')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_cases', to='reports.symptomreport')),
                ('risk_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_case', to='decision_engine.riskassessment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
