# Generated by Django 6.0.4 on 2026-04-27 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('WORKFLOW_VALIDATED', 'Workflow validated'), ('WORKFLOW_ACTIVATED', 'Workflow activated'), ('WORKFLOW_ARCHIVED', 'Workflow archived'), ('FOLLOW_UP_CASE_CREATED', 'Follow-up case created'), ('FOLLOW_UP_CASE_STATUS_CHANGED', 'Follow-up case status changed'), ('SYMPTOM_REPORT_SUBMITTED', 'Symptom report submitted'), ('RISK_ASSESSMENT_CREATED', 'Risk assessment created'), ('ADVICE_CREATED', 'Advice created'), ('ESCALATION_CREATED', 'Escalation created'), ('ESCALATION_UPDATED', 'Escalation updated'), ('APPOINTMENT_CREATED', 'Appointment created'), ('APPOINTMENT_UPDATED', 'Appointment updated')], max_length=64)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
