# Generated by Django 6.0.4 on 2026-04-27 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decision_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('LOW_RISK_AFTERCARE', 'Low-risk aftercare'), ('WARNING_MONITORING', 'Warning monitoring'), ('HIGH_STAFF_REVIEW', 'High staff review'), ('URGENT_ATTENTION', 'Urgent attention')], max_length=40)),
                ('source', models.CharField(choices=[('TEMPLATE', 'Template')], default='TEMPLATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advice_message', to='decision_engine.riskassessment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
