# Generated by Django 6.0.4 on 2026-04-26 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0002_alter_escalationrule_target_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('dental_notes', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('MONITORING', 'Monitoring'), ('AI_GUIDANCE_PROVIDED', 'AI Guidance Provided'), ('ESCALATED', 'Escalated'), ('APPOINTMENT_REQUIRED', 'Appointment Required'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_follow_up_cases', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_cases', to='workflows.treatmentworkflow')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_cases', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-treatment_date', '-id'],
            },
        ),
    ]
